Default filter on LogName 'System,Security,Setup,Application' - fix issue #1
mattpodwysocki/win-getevent pull request #4
Opened 2016-12-04 16:07 UTC by megastef

2016-12-04 16:09 UTC, megastef commented
Please note, I could not implement provider: *  - somehow the Get-WindowsEvent CLI did not like wildcards or combine ListLogs * with time filter. Therefor I finally added LogName filter, which has good defaults.

2016-12-05 16:33 UTC, mattpodwysocki commented
@megastef please add back in the semicolons, that's outside the scope of this change.  We can discuss that other change separately.

2016-12-05 17:49 UTC, megastef commented
Semicolons should be in again.

2016-12-06 10:57 UTC, megastef commented
@mattpodwysocki do you plan to merge and publish this?

2016-12-06 11:38 UTC, mattpodwysocki commented
@megastef yes but can you address those comments I had above?

2016-12-06 14:44 UTC, megastef commented
Yes. The Semicolons are back (reverted my last commit).

2016-12-06 15:10 UTC, mattpodwysocki requested changes

2016-12-06 15:10 UTC, mattpodwysocki commented on lib/WinEventEmitter.js
> +        creds =  `$User = '${this.options.userName}'; $Pass = ConvertTo-SecureString -String '${this.options.password}' -AsPlainText -Force; $Credential = New-Object â€“TypeName 'System.Management.Au
What is this symbol here?  It doesn't seem to be a simple `-`, so what is it?

2016-12-06 15:10 UTC, mattpodwysocki commented on lib/WinEventEmitter.js
> +        this.emit('raw.data', data)
Should emitting be moved outside of the try?  What reason is it there to be protected?

2016-12-06 15:10 UTC, mattpodwysocki commented on lib/WinEventEmitter.js
> +          this.emit('data', parsedData)
Same comment as above, why is emitting inside the try block because it shouldn't need to be protected, especially if the `parsedData` is declared outside the try/catch block

2016-12-06 15:10 UTC, mattpodwysocki commented
@megastef woops, sorry, I needed to publish my comments.  Please address those now.

2016-12-06 17:22 UTC, megastef commented on lib/WinEventEmitter.js
> +        creds =  `$User = '${this.options.userName}'; $Pass = ConvertTo-SecureString -String '${this.options.password}' -AsPlainText -Force; $Credential = New-Object â€“TypeName 'System.Management.Au
Sorry, I assume notepad.exe or some other tool (remote desktop?) produced this. I had no windows-pc and used remote desktop from a Mac.

2016-12-06 17:25 UTC, mattpodwysocki approved these changes

2016-12-06 17:25 UTC, merged